### ISSUE TITLE
Does it support python 3.11?

### ISSUE THREAD

**Issue by Tobeabellwether** [camelot-dev/camelot#362] opened 2023-03-31 19:18 UTC
**Describe the bug**

Dear camelot team, when I use poetry to add `"camelot-py[base]"`, I found that installation for `pdftopng` failed, it raised the error: `Unable to find installation for pdftopng(0.2.3)`, I'm using `python 3.11`. Thanks

**Comment by rossettistone** [comment] 2023-04-21 15:57
Seems like this is caused by `pdftopng` not having a 3.11 (or 3.10) build. https://github.com/vinayak-mehta/pdftopng/issues/11

Last commit on `pdftopng` was back in 2021, so it seems unlikely that this'll be fixed on their end soon.

I'm sorry to say I don't have a workaround. Just providing the above info for others stumbling on this issue.

**Comment by maxkeiko** [comment] 2023-04-26 02:17
"`camelot-py[base]`" seems not good. It works for me with "`camelot-py`" in python 3.11.

**Comment by aoyono** [comment] 2023-04-30 08:11
I think I found a workaround for `pdftopng` v0.2.3, which can be used to workaround any install issue with `camelot` as well. In my case, I couldn't install it on Python 3.11 with the "[cv]" extra. The workaround below solved it:

1. Apply [this workaround](https://github.com/vinayak-mehta/pdftopng/issues/11#issuecomment-1528965275) for `pdftopng` (disclaimer: I am the author)
2. Once `pdftopng` is installed, you can install `camelot-py` with the [cv] extra: `python3 -m pip install "camelot-py[cv]==0.11.0"`

**Comment by foarsitter** [comment] 2023-09-24 14:12
See https://github.com/camelot-dev/camelot/issues/394 for details.

**Closed by foarsitter** 2023-09-24 14:12 UTC
Labels: bug
